Add native support for new (Slackware 15.0) local packages directory
rg3/slackroll pull request #14
Opened 2018-08-23 22:59 UTC by aclemons

This mimics the fallback behaviour for choosing a GPG version, by first
checking if the new packages location exists, otherwise checking for the
old packages directory.

2018-08-24 10:01 UTC, rg3 requested changes
I've searched for "/var/log/packages" in other source files and there are quite a few mentions inside helpfiles:

* helpfiles/local-search.txt
* helpfiles/local-info.txt
* helpfiles/all.txt
* helpfiles/manifest-search.txt
* helpfiles/info.txt
* helpfiles/missing-search.txt

I think there are two reasonable options. The first one is to keep the documentation as it is, using the traditional and known path as long as the compatibility symlinks don't go away. This probably won't confuse the reader. When the symlinks are removed, most users should know about the new path and it should be updated.

The second option is coming up with a name for that directory and its contents, like "pkgtool's installed packages database" or a similar expression and use it consistently everywhere in the documentation.

Or if you have another better idea, it's your call.

2018-08-24 10:01 UTC, rg3 commented on slackroll
> +slackroll_local_pkgs_glob = os.path.join(os.path.sep, yield_slackroll_local_pkgs_dir().next(), '*')
The first os.path.sep argument here is not needed, I think, because you're already getting a full path from the yielding function. Other than that, everything looks good to me. If you've tested this under -current and 14.2 and you've seen the program choose both paths, that's perfect. :+1:

2018-08-24 10:01 UTC, rg3 commented on slackroll
> +def get_local_pkgs(): # Return a list of packages from slackroll_local_pkgs_dir
This change needs to be done for the comment at get_pkg_filelists too.

2020-02-05 18:28 UTC, rg3 commented
@aclemons Ping! This PR was left with requested changes that were never completed. Are you still using Slackware?

2020-02-06 22:01 UTC, aclemons commented
Yes I am. I'll update this PR and ping you back.

2020-02-06 22:13 UTC, rg3 commented
That's great to hear. Thanks, Andrew!

2020-02-09 05:16 UTC, aclemons commented on slackroll
> +def get_local_pkgs(): # Return a list of packages from slackroll_local_pkgs_dir
I've updated this one

2020-02-09 05:16 UTC, aclemons commented on slackroll
> +slackroll_local_pkgs_glob = os.path.join(os.path.sep, yield_slackroll_local_pkgs_dir().next(), '*')
I've removed this first one.

2020-02-09 05:19 UTC, aclemons commented
Regarding the references to /var/log/packages in the help files, I started changing this to your suggestion but some of them make less sense then, i.e. local-info.txt

```
It was added because it is usually faster to type "slackroll local-info PKG"
than to run "less /var/log/packages/PKG-something", but other than that they
are mostly equivalent.
```
Changing that one won't help much.

I think the best would be to leave the help as is for now, let 15.0 be released (it has still not been released) and then potentially change it to the new directory, or even possibly wait for another release after that. I highly doubt Pat will take the backwards compatibility symlink out any time soon.

2020-02-09 10:10 UTC, rg3 commented
> Regarding the references to /var/log/packages in the help files, I started changing this to your suggestion but some of them make less sense then, i.e. local-info.txt
> 
> ```
> It was added because it is usually faster to type "slackroll local-info PKG"
> than to run "less /var/log/packages/PKG-something", but other than that they
> are mostly equivalent.
> ```
> 
> Changing that one won't help much.
> 
> I think the best would be to leave the help as is for now, let 15.0 be released (it has still not been released) and then potentially change it to the new directory, or even possibly wait for another release after that. I highly doubt Pat will take the backwards compatibility symlink out any time soon.

In a second look, that sounds reasonable, so lets go with that plan.

2020-02-09 10:11 UTC, merged